# CodeRabbit Configuration
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"

reviews:
  # Enable auto-review for PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  # Review profile
  profile: "assertive"

  # Request changes workflow
  request_changes_workflow: false

  # High-level summary placement
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  # Enable poem generation for fun
  poem: true

  # Review status
  review_status: true

  # Collapse walkthrough
  collapse_walkthrough: false

  # Path filters - exclude certain paths from review
  path_filters: []

  # Path instructions for specific paths
  path_instructions: []

chat:
  # Enable chat features
  auto_reply: true

# Knowledge base for the project
knowledge_base:
  # Organization-level knowledge
  opt_out: false

  # Learnings - enable learning from past interactions
  learnings:
    scope: "auto"

# Early access features
early_access: false

# Tools configuration
tools:
  # Shellcheck for shell scripts
  shellcheck:
    enabled: true

  # Ruff for Python linting
  ruff:
    enabled: true

  # Markdownlint for markdown files
  markdownlint:
    enabled: true

  # GitHub checks
  github-checks:
    enabled: true
    timeout_ms: 90000
